[phases.setup]
nixPkgs = ["python314", "python314Packages.pip"]
aptPackages = [
  "build-essential",
  "python3-dev",
  "libopenblas-dev",
  "liblapack-dev",
  "libomp-dev"
]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "sh -c 'uvicorn main:app --host 0.0.0.0 --port $MLPORT --workers 1'"